#!/bin/bash
#
# vils-ng
#
# see https://github.com/simonschiele/vils-ng for details
#

LANG=C
TMP="${HOME}/.vils-ng.$$.tmp"
PREPEND=6

HELP=false
RECURSIVE=false
GUI=false
DRYRUN=false
DEBUG=false
MAXDEPTH=
VERBOSE=
ECHO=

case "$(uname -s)" in
  Linux*)   MD5SUM="md5sum";;
  Darwin*)  MD5SUM="md5 -q";;
esac

function cleanup() {
    rm -f "$TMP" "$TMP".new
    exit 1
}

function help() {
    echo -e "vils-ng [options] [file1] [file2] [file3] [...]" >&2
    echo -e "" >&2
    echo -e 'Mass-renaming with your favorite editor!' >&2
    echo -e "" >&2
    echo -e "Options:" >&2
    echo -e " -h\thelp" >&2
    echo -e " -r\trecursive" >&2
    echo -e " -v\tverbose" >&2
    echo -e " -d\tdry-run (only print what would be done, do not actually move files)" >&2
    echo -e " -D\tdebug" >&2
    echo -e " -x\tuse x11 editor" >&2
    echo -e "" >&2
    echo -e "Usage examples:" >&2
    echo -e "" >&2
    echo -e " # rename files in current dir:" >&2
    echo -e " > vils-ng" >&2
    echo -e "" >&2
    echo -e " # rename specific files:" >&2
    echo -e " > vils-ng testfile1.txt testfile2.mkv testdir/testfile3.log" >&2
    echo -e "" >&2
    echo -e " # rename files in current dir and all subdirs:" >&2
    echo -e " > vils-ng -r" >&2
    echo -e "" >&2
    exit 0
}

function vils_ng() {

    while getopts ":hxrdDv" opt; do
        case $opt in
            h)
                HELP=true
                ;;
            x)
                GUI=true
                ;;
            r)
                RECURSIVE=true
                ;;
            d)
                DRYRUN=true
                ;;
            D)
                DEBUG=true
                ;;
            v)
                VERBOSE="-v"
                ;;
            \?)
                echo "Unknown Option: -$OPTARG" >&2
                exit 1
                ;;
        esac
    done

    if ( $DEBUG )
    then
        echo ""
        echo "Called as:"
        echo " $0 $@"
        echo ""
        echo "Config"
        echo " DEBUG: true"
        echo " HELP: $HELP"
        echo " GUI: $GUI"
        echo " RECURSIVE: $RECURSIVE"
        echo " DRYRUN: $DRYRUN"
        echo " VERBOSE: $VERBOSE"
        echo ""
    fi

    shift $((OPTIND-1))

    if ( $HELP )
    then
        help
    fi

    # Setup trap for cleanup on interrupt
    trap cleanup 1 2 3 15

    if ( ! $RECURSIVE )
    then
        MAXDEPTH="-maxdepth 1"
    fi

    if ( $DRYRUN )
    then
        ECHO="echo"
    fi

    if [[ -n "${@}" ]]
    then
        ls -d -- $@ | awk '{printf "%0'${PREPEND}'d %s\n", NR, $0}' > "$TMP"
    else
        find . -mindepth 1 ${MAXDEPTH} -type d -exec sh -c 'printf "%s/\n" "$0"' {} \; -or -print | sed 's|^./||g' | awk '{printf "%0'${PREPEND}'d %s\n", NR, $0}' > "$TMP"
    fi
    cp "$TMP" "$TMP".new

    if ( $GUI )
    then
        ${VISUAL:-/usr/bin/gvim} "$TMP".new
    else
        ${EDITOR:-/usr/bin/vi} "$TMP".new
    fi

    validate_checksum=$( sed 's|\t|\ |g' "$TMP" | grep -v '^\ *$' | sed 's|^\([0-9]*\ \)\(.*\)$|\1|g' | $MD5SUM | awk {'print $1'} )
    validate_checksum_new=$( sed 's|\t|\ |g' "$TMP".new | grep -v '^\ *$' | sed 's|^\([0-9]*\ \)\(.*\)$|\1|g' | $MD5SUM | awk {'print $1'} )

    if [ "$validate_checksum" != "$validate_checksum_new" ]
    then
        echo "Canceling rename. Illegal changes to filelist." >&2
        exit 1
    elif [ $( $MD5SUM "$TMP" | awk {'print $1'} ) != $( $MD5SUM "$TMP".new | awk {'print $1'} ) ]
    then
        cat "$TMP" | while read line
        do
            linenr=$( echo "$line" | sed 's|^\([0-9]*\ \)\(.*\)$|\1|g' )
            filename=$( echo "$line" | sed 's|^\([0-9]*\ \)\(.*\)$|\2|g' )
            new_filename=$( grep "^${linenr}" "$TMP".new | cut -f'2-' -d' ' )
            if [ "$filename" != "$new_filename" ]
            then
                $ECHO mkdir -p $( dirname "${new_filename}" )
                $ECHO mv ${VERBOSE} -i "${filename}" "${new_filename}"
            fi
        done
    else
        echo "No changes. Nothing renamed or moved."
    fi

    rm -f "$TMP" "$TMP".new
    exit 0
}

vils_ng "${@}"
